version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  nats:
    image: nats:alpine
    container_name: nats-basic
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./config/nats.conf:/etc/nats/nats.conf
    networks:
      - monitor-net

