version: '3.8'

networks:
  monitor-net:
    driver: bridge

services:
  nats:
    image: nats:alpine
    container_name: nats
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    networks:
      - monitor-net

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    restart: always
    command: [
      "nats-streaming-server",
      "--store", "file",
      "--dir", "/data",
      "--cluster_id", "test-cluster",
      "--nats_server", "nats://token_usuario1:password_segura@nats:4222"
    ]
    ports:
      - "4223:4223" # NATS Streaming client port
    volumes:
      - ./nats-streaming/data:/data
    networks:
      - monitor-net
    depends_on:
      - nats
